src/Entity/Rencontre.php
<?php

namespace App\Entity;

use App\Repository\RencontreRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: RencontreRepository::class)]
class Rencontre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: false)]
    #[Assert\NotBlank]
    private ?string $competition = null;

    #[ORM\Column(length: 255, nullable: false)]
    #[Assert\NotBlank]
    private ?string $Adversaire = null;

    #[ORM\Column(length: 255, nullable: false)]
    #[Assert\NotBlank]
    private ?string $Type = null;

    #[ORM\Column(length: 255, nullable: false)]
    #[Assert\NotBlank]
    private ?string $resultat = null;

    #[ORM\Column(length: 255, nullable: false)]
    #[Assert\NotBlank]
    private ?string $Score = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: false)]
    #[Assert\NotBlank]
    private ?\DateTimeInterface $date = null;

    #[ORM\ManyToOne(inversedBy: 'rencontre')]
    private ?User $user = null;

    #[ORM\Column(length: 10, nullable: false)]
    #[Assert\NotBlank]
    private ?string $classement = null;

    #[ORM\Column(length: 100, nullable: false)]
    #[Assert\NotBlank]
    private ?string $saison = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCompetition(): ?string
    {
        return $this->competition;
    }

    public function setCompetition(string $competition): static
    {
        $this->competition = $competition;

        return $this;
    }

    public function getAdversaire(): ?string
    {
        return $this->Adversaire;
    }

    public function setAdversaire(string $Adversaire): static
    {
        $this->Adversaire = $Adversaire;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->Type;
    }

    public function setType(string $Type): static
    {
        $this->Type = $Type;

        return $this;
    }

    public function getResultat(): ?string
    {
        return $this->resultat;
    }

    public function setResultat(string $resultat): static
    {
        $this->resultat = $resultat;

        return $this;
    }

    public function getScore(): ?string
    {
        return $this->Score;
    }

    public function setScore(string $Score): static
    {
        $this->Score = $Score;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getClassement(): ?string
    {
        return $this->classement;
    }

    public function setClassement(string $classement): static
    {
        $this->classement = $classement;

        return $this;
    }

    public function getSaison(): ?string
    {
        return $this->saison;
    }

    public function setSaison(string $saison): static
    {
        $this->saison = $saison;

        return $this;
    }
}

src/Controller/ActivityController.php
<?php

namespace App\Controller;

use App\Entity\Rencontre;
use App\Form\ShowByYearType;
use App\Form\NewMatchFormType;
use App\Repository\RencontreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ActivityController extends AbstractController
{
    // Matchs affichés par dates décroissantes
    // #[Route('/matchs', name: 'app_matchs', methods: ['GET'])]
    // public function userAllMatchs(
    //     RencontreRepository $RencontreRepository,
    //     PaginatorInterface $paginator,
    //     Request $request
    // ): Response
    // {
    //     $data = $RencontreRepository->findAllByDateDESC();
    //     $rencontres = $paginator->paginate(
    //     $data,
    //     $request->query->getInt('page', 1)
    //     );
        
    //     return $this->render('activity/matchs.html.twig', [
    //         'rencontres'=> $rencontres,
    //     ]);
    // }

    #[Route('/matchs', name: 'app_matchs', methods: ['GET'])]
    public function allMatchsUserCurrentAndSelectedYear(
    RencontreRepository $RencontreRepository,
    PaginatorInterface $paginator,
    Request $request
    ): Response
    {
    // Création du formulaire
    $form = $this->createForm(ShowByYearType::class);
    $form->handleRequest($request);

    // Si une année est sélectionnée
    if ($form->isSubmitted() && $form->isValid()) {
        $year = $form->get('year')->getData();
        // Récupérer les rencontres filtrées par l'année
        $data = $RencontreRepository->findByYear($year);
    } else {
        // Si aucune année sélectionnée, récupérer toutes les rencontres
        $data = $RencontreRepository->findByCurrentYear();
    }

    $rencontres = $paginator->paginate(
        $data,
        $request->query->getInt('page', 1), 7
    );

    return $this->render('activity/matchs.html.twig', [
        'rencontres' => $rencontres,
        'form' => $form->createView(), 
    ]);
    }



    // Ajouter un match au palmarès de l'utilisateur connecté
    #[Route('/matchs/ajout', name: 'app_matchs_add')]
    public function add(
        Request $request,
        EntityManagerInterface $em
        ): Response
    {
        $rencontre = new Rencontre();

        $user = $this->getUser();

        $rencontre->setUser($user);

        $form = $this->createForm(NewMatchFormType::class, $rencontre);
        $form->handleRequest($request);

        

        if ($form->isSubmitted() && $form->isValid()) {
            
            $em->persist($rencontre);
            $em->flush();

            $this->addFlash('success', 'Votre match est désormais consultable dans votre palmarès');

            return $this->redirectToRoute('app_matchs');
        }

        return $this->render('Form/_add_match_form.html.twig', [
            'matchForm' => $form->createView(),
        ]);
    }

    // Supprimer un match
    #[Route('/matchs/supprimer/{id}', name: 'app_matchs_delete')]
    public function delete (
        Rencontre $rencontre,
        EntityManagerInterface $em
        ): Response
    {
        
        $em->remove($rencontre);
        $em->flush();

        $this->addFlash('success', 'Votre match à bien été supprimé');

        return $this->redirectToRoute('app_matchs');

    }

    // Modifier un match dans le palmarès
    #[Route('/matchs/edit/{id}', name: 'app_matchs_edit')]
    public function edit (
        Rencontre $rencontre,
        Request $request,
        EntityManagerInterface $em
        ): Response
    {

        if ($rencontre === null) {
            throw $this->createNotFoundException('Match non trouvé.');
        }
        
        $form = $this->createForm(NewMatchFormType::class, $rencontre);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {

            $rencontre = $form->getData();

            $em->persist($rencontre);
            $em->flush();

            $this->addFlash('success', 'Votre match à bien été modifié');

            return $this->redirectToRoute('app_matchs');
        }

        return $this->render('Form/_add_match_form.html.twig', [
            'matchForm' => $form->createView(),
        ]);

    }

}

templates/activity/matchs.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<div class="justify-center">
    <h1 class="text-3xl text-center font-bold mt-10">Palmarès</h1>
</div>

<div class="max-w-7xl mx-auto overflow-auto">

    {{ include('components/_flash_message.html.twig') }}

    <div class="flex justify-between items-center w-full mt-5">
        <a href ="{{ path('app_matchs_add') }}" class="btn text-black p-3 rounded-xl font-bold">
            Ajouter un match
        </a>
    
        <div class="w-40">
            {{ form_start(form, {'attr': {'class': 'space-y-4'}}) }}
            <div class="mb-4">
                {{ form_widget(form.year, {
                    'attr': {
                        'class': 'mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm',
                        'onchange': 'this.form.submit();' 
                    },
                    'placeholder': 'Année'
                }) }}
                {{ form_errors(form.year, {'attr': {'class': 'text-red-600 text-sm'}}) }}
            </div>
        
            {{ form_end(form) }}
        </div>
        
    </div>
    

    <div class="inline-block min-w-full py-2 align-middle">
        <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
            <table class="min-w-full divide-y divide-gray-300">
                <thead class="bg-green-700">
                    <tr>
                        <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Date</th>
                        <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900">Compétition</th>
                        <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Adversaire</th>
                        <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Classement</th>
                        <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Score</th>
                        <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Résultat</th>
                        <th scope="col" class="relative text-right py-3.5 pl-3 pr-4 sm:pr-6">
                            <span class="sr-only">Actions</span>
                        </th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-gray-200 bg-white">
                    {% for rencontre in rencontres %}
                    
                    {% if rencontre.user == app.user %}
                    <tr>
                        <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-semibold text-gray-900 sm:pl-6">{{ rencontre.date|date("d/m/Y", "Europe/Paris") }}</td>
                        <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ rencontre.competition }}</td>
                        <td class="whitespace-nowrap px-3 py-4 text-sm">
                            {{ rencontre.adversaire }}
                        </td>
                        <td class="whitespace-nowrap px-3 py-4 text-sm">
                            {{ rencontre.classement }}
                        </td>
                        <td class="whitespace-nowrap px-3 py-4 text-sm">
                            {{ rencontre.score }}
                        </td>
                        <td class="whitespace-nowrap px-3 py-4 text-sm text-green-300 font-semibold {% if rencontre.resultat == 'Victoire' %}text-green-500{% elseif rencontre.resultat == 'Défaite' %}text-red-500{% endif %}">
                            {{ rencontre.resultat }}
                        </td>
                        <td class="py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                            <div class="inline-block text-left" x-data="{ menu: false }">
                                <button x-on:click="menu = ! menu" type="button" class="flex items-center text-gray-400 hover:text-gray-600 focus:outline-none" id="menu-button" aria-expanded="true" aria-haspopup="true">
                                    <span class="sr-only"></span>
                                    <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                    <path d="M10 6a2 2 0 110-4 2 2 0 010 4zM10 12a2 2 0 110-4 2 2 0 010 4zM10 18a2 2 0 110-4 2 2 0 010 4z" />
                                    </svg>
                                </button>
                                <div x-show="menu" x-on:click.away="menu = false" class="origin-top-right absolute right-32 mt-2 w-56 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 divide-y divide-gray-100 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
                                    <div class="" role="none">
                                        <a href="{{ path('app_matchs_edit', {'id':rencontre.id}) }}" class="text-gray-500 font-medium hover:text-gray-900 hover:bg-gray-50 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">
                                            Modifier
                                        </a>
                                    </div>
                                    <div class="" role="none">
                                        <a href={{ path('app_matchs_delete', {'id':rencontre.id}) }} class="text-gray-500 font-medium hover:text-gray-900 hover:bg-gray-50 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0" onclick="return confirm('Voulez-vous supprimer cet enregistrement ?');">
                                            Supprimer
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <!-- Pagination -->
    <div class="navigation flex justify-center mt-5 mb-5">
        {{ knp_pagination_render(rencontres) }}
    </div>
 
</div>

<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.8.2/dist/alpine.min.js" defer></script>
  
{% endblock %}